/*
 * Swagger Citizen API
 * null
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package id.koneko096.grpc.data.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.LocalDate;

/**
 * Citizen
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-20T21:21:26.411+07:00")
public class Citizen {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("birthday")
  private LocalDate birthday = null;

  public Citizen id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Citizen firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Citizen First Name
   * @return firstName
  **/
  @ApiModelProperty(value = "Citizen First Name")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public Citizen lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Citizen Last Name
   * @return lastName
  **/
  @ApiModelProperty(value = "Citizen Last Name")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public Citizen birthday(LocalDate birthday) {
    this.birthday = birthday;
    return this;
  }

   /**
   * Citizen Birthday
   * @return birthday
  **/
  @ApiModelProperty(value = "Citizen Birthday")
  public LocalDate getBirthday() {
    return birthday;
  }

  public void setBirthday(LocalDate birthday) {
    this.birthday = birthday;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Citizen citizen = (Citizen) o;
    return Objects.equals(this.id, citizen.id) &&
        Objects.equals(this.firstName, citizen.firstName) &&
        Objects.equals(this.lastName, citizen.lastName) &&
        Objects.equals(this.birthday, citizen.birthday);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, firstName, lastName, birthday);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Citizen {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    birthday: ").append(toIndentedString(birthday)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

