/*
 * Swagger Citizen API
 * null
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package id.koneko096.grpc.api;

import id.koneko096.grpc.data.model.Citizen;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for CitizenApi
 */
@Ignore
public class CitizenApiTest {

    private final CitizenApi api = new CitizenApi();

    
    /**
     * Create citizen
     *
     * Creates a new Citizen
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCitizenTest() {
        Citizen response = api.createCitizen();

        // TODO: test validations
    }
    
    /**
     * Delete citizen by ID
     *
     * Deletes a single Citizen
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCitizenTest() {
        Long citizenId = null;
        api.deleteCitizen(citizenId);

        // TODO: test validations
    }
    
    /**
     * List citizens
     *
     * Returns list of Citizen
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCitizensTest() {
        List<Citizen> response = api.getAllCitizens();

        // TODO: test validations
    }
    
    /**
     * Find citizen by ID
     *
     * Returns a single Citizen
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCitizenDetailsTest() {
        Long citizenId = null;
        Citizen response = api.getCitizenDetails(citizenId);

        // TODO: test validations
    }
    
    /**
     * Update citizen
     *
     * Updates an existing Citizen
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCitizenTest() {
        Long citizenId = null;
        Citizen response = api.updateCitizen(citizenId);

        // TODO: test validations
    }
    
}
